# How to install numpy

In [ ]:
pip install numpy

In [ ]:
# import the numpy package

import numpy as np

# Create 1-D array

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


# Create Multi Dimen array

In [ ]:
a = np.array([[1,2,3],[10,20,30]])

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creates a number between start and end and number of elements which will be equally distributed
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(a.dtype)

int64


# Numpy array vs list memory allocation

In [ ]:
l = range(1000)
print(type(l))
import sys
a = 10
print(sys.getsizeof(a)) # momery located to a
print(sys.getsizeof(a)*len(l))

a1 = np.arange(1000)
print(a1.size)
print(a1.size*a1.itemsize)

<class 'range'>
28
28000
1000
8000


# Numpy vs List Speed

In [ ]:
import time
import sys

In [ ]:
size = 1000000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list itemwise sum
start = time.time()
result = [ (x +y) for x,y in zip(l1,l2)]
print((time.time() - start)*1000)

#numpy array itemwise sum
start = time.time()
result = n1+n2
print((time.time() - start)*1000)

180.21535873413086
13.826847076416016


#Numpy Operations

In [ ]:
a = np.array([[1,2,3],[10,20,30]])
print(a.ndim)

2


In [ ]:
print(a.itemsize)

8


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
#Total no of elements
print(a.size)

6


# Reshape

In [ ]:
#Changing the rows size or columns size or vice versa
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a.reshape((3,2))

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = a.reshape(3,2) #3*2 = 6
print(a)

#OR
np.reshape(a,(2,3))

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(a)
print(a.size)
np.reshape(a,6)

[[0 1]
 [2 3]
 [4 5]]
6


array([0, 1, 2, 3, 4, 5])

In [ ]:
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(a.flatten())

[0 1 2 3 4 5]


# Slicing

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a[0,0] # individual access

1

In [ ]:
a[0,1]  # individual access

2

In [ ]:
a[0:,1]

array([ 2, 20])

In [ ]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
a[0:2,1:]

array([[ 2,  3],
       [20, 30]])

In [ ]:
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [ ]:
a.shape

(2, 5)

In [ ]:
a[1,2:4]

array([30, 40])

In [ ]:
print(a.max())

50


In [ ]:
print(a.sum())

165


In [ ]:
print(a)
print(np.sum(a,axis = 0)) # row wise sum

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[11 22 33 44 55]


In [ ]:
print(a)
print(np.sum(a,axis = 1)) # column wise sum

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[ 15 150]


# Array Mathematical Operations

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(y)

print(x+y)

#OR

print(np.add(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(np.multiply(x,y))
#OR
print(x*y)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
print(x-y)
#OR
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# PANDAS

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.array(['w','e','l','c','o','m','e'])
p = pd.Series(a)
print(p)

0    w
1    e
2    l
3    c
4    o
5    m
6    e
dtype: object


In [ ]:
s1 = pd.Series(np.random.random(5), index = ['a','b','c','d','e'])

In [ ]:
print(type(s1))
print(s1)
print(s1.dtype)

<class 'pandas.core.series.Series'>
a    0.693508
b    0.372186
c    0.458174
d    0.834085
e    0.854814
dtype: float64
float64


In [ ]:
data ={'pi':3.14,'e':2.71}
print(data)
print(type(data))

s3 = pd.Series(data)
print(s3)

{'pi': 3.14, 'e': 2.71}
<class 'dict'>
pi    3.14
e     2.71
dtype: float64


In [ ]:
s = pd.Series(np.random.random(5))
print(s)

0    0.792459
1    0.214494
2    0.179231
3    0.340958
4    0.770510
dtype: float64


In [ ]:
s[1]

0.21449411651918238

In [ ]:
s[1:3]

1    0.214494
2    0.179231
dtype: float64

In [ ]:
#indexes
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [ ]:
print(s.ndim)

1


In [ ]:
print(s.size)

5


In [ ]:
print(s.shape)

(5,)


In [ ]:
print(s.head)

<bound method NDFrame.head of 0    0.792459
1    0.214494
2    0.179231
3    0.340958
4    0.770510
dtype: float64>
