KNN - K-Nearest Neighbours

URL:https://www.youtube.com/watch?v=7e7bsb2RivU 

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
df = pd.DataFrame(iris.data)
df.columns = iris.feature_names
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
X = df
y = iris.target

In [ ]:
#splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)
# 3 Shortest distance data point will be taken

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

# Predictions and Accuracy

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
iris.target_names[y_pred]

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'virginica'], dtype='<U10')

In [ ]:
x_new = np.array([[5,2.9,1,0.2]])

In [ ]:
prediction = knn.predict(x_new)
prediction

array([0])

In [ ]:
iris['target_names'][prediction]

array(['setosa'], dtype='<U10')

# Accuracy

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [ ]:
accuracy_score(y_test, y_pred)

0.9736842105263158

In [ ]:
cr = classification_report(y_test, y_pred)
cr

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        13\n           1       1.00      0.94      0.97        16\n           2       0.90      1.00      0.95         9\n\n    accuracy                           0.97        38\n   macro avg       0.97      0.98      0.97        38\nweighted avg       0.98      0.97      0.97        38\n'

# K-Fold Cross Validation

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
X = iris.data
y = iris.target

In [ ]:
from sklearn.model_selection import cross_val_score

# 3 Ml module used for the performance comparision
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Logistic Regression

In [ ]:
# Logistic Regression score

# K fold value is 5

lr_score = cross_val_score(LogisticRegression(), X,y)
lr_score

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [ ]:
np.average(lr_score)

0.9733333333333334

# Decision Tree

In [ ]:
# Decision Tree Score
dt_score = cross_val_score(DecisionTreeClassifier(), X, y)
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [ ]:
np.average(dt_score)

0.9600000000000002

# Support Vector Machine

In [ ]:
# SVM
svm_score = cross_val_score(SVC(), X, y)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [ ]:
np.average(svm_score)

0.9666666666666666

In [ ]:
# It can be inferred as per the above technique that the Logistic Regresiion has the highest accuracy

# K fold cross validation

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
lr_score = cross_val_score(LogisticRegression(), X,y, cv = kf)
lr_score

array([0., 0., 0.])

In [ ]:
# Online Code

# evaluate a logistic regression model using k-fold cross-validation
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
# create dataset
X, y = make_classification(n_samples=100, n_features=20, n_informative=15, n_redundant=5, random_state=1)
# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=1, shuffle=True)
# create model
model = LogisticRegression()
# evaluate model
scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.850 (0.128)


# WEB SCRAPING

In [ ]:
#libraries in python for web scraping

#Selenium
#Beatifulsoup
#Pandas