***Name: SADDAM HUSSIN***

***REG ID: GO_STP_6834***



---



1. Import the numpy package under the name np and Print the numpy version and the configuration

In [ ]:
import numpy as np

In [ ]:
np.version.version

'1.19.5'

In [ ]:
# OR

np.__version__

'1.19.5'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


2. Create a null vector of size 10

In [ ]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create Simple 1-D array and check type and check data types in array

In [ ]:
array = np.array([1,2,3])
print(array)
print(type(array))
print(array.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


4. How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
#Dimension of an array , 1D, 2D or 3D etc
array.ndim

1

In [ ]:
array.shape

(3,)

In [ ]:
array.size

3

In [ ]:
#Memory
import sys

#Momory Used
sys.getsizeof(array)

120

In [ ]:
#Bytes per element
array.itemsize

8

5. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Create a vector with values ranging from 10 to 49

In [ ]:
data = np.arange(10,50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

7. Reverse a vector (first element becomes last)

In [ ]:
print(data[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
data = np.array([[0,1,2],[3,4,5],[6,7,8]])
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#OR
data = np.arange(9)
newVector = data.reshape(3,3)
newVector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
data = np.array([1,2,0,0,4,0])

#indices of non zero element
indices = np.nonzero(data)
print(indices)

#non zero elements
print(data[indices])

(array([0, 1, 4]),)
[1 2 4]


10. Create a 3x3 identity matrix

In [ ]:
data = np.ones(9)
print(data.reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


11. Create a 3x3x3 array with random values

In [ ]:
data = np.random.random(size=[3,3,3])
data

array([[[0.72336429, 0.47527545, 0.0674571 ],
        [0.79256558, 0.91566728, 0.36013676],
        [0.88668849, 0.5176543 , 0.66976295]],

       [[0.18193849, 0.72853061, 0.08888202],
        [0.7866261 , 0.94460196, 0.8763229 ],
        [0.78339597, 0.95499859, 0.35494576]],

       [[0.15490929, 0.83367569, 0.20380429],
        [0.50687942, 0.4360467 , 0.50547629],
        [0.48764912, 0.10373019, 0.97632764]]])

12. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
data = np.random.random((10,10))
max = data.max()
print(max)

min = data.min()
print(min)

0.9846445112530668
0.03835439992038969


13. Create a random vector of size 30 and find the mean value

In [ ]:
data = np.array(30)
data.mean()

30.0

14. Create a 2d array with 1 on the border and 0 inside

In [ ]:
data = np.array([[1,1,1],[1,0,1],[1,1,1]])
data

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
#OR
data = np.ones([3,3])
print("Before Zero ")
print(data)
data[1:-1,1:-1] = 0
print("\nAfter Zero ")
print(data)

Before Zero 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

After Zero 
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [ ]:
#OR
data = np.zeros([4,4])
print("Before Zero ")
print(data)

data[1:-1,1:-1] = 1
print("\nAfter Zero ")
print(data)

Before Zero 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

After Zero 
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#OR
a = np.arange(1,17).reshape(4,4)
print(a)

a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  0]
 [ 0  5  6  7  8  0]
 [ 0  9 10 11 12  0]
 [ 0 13 14 15 16  0]
 [ 0  0  0  0  0  0]]


16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -

[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20



In [ ]:
data = np.array([[1,2,3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
data[1,5]

13

In [ ]:
data[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
data[:,2]

array([ 3, 10])

In [ ]:
data[0,[1,3,5]]

array([2, 4, 6])

In [ ]:
data[1,5] = 20
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

17. How to Convert a 1D array to a 2D array with 2 rows

In [ ]:
oneDArray = np.arange(8)
twoDArray = oneDArray.reshape([2,4])
twoDArray

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [ ]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19. Write a program to show how Numpy taking less memory compared to Python List?

In [ ]:
l = range(8000)
print(type(l))
import sys
a = 10
print("For List")
print(sys.getsizeof(a)) # momery located to a
print(sys.getsizeof(a)*len(l))

print('\n')
print("For Numpy")
a1 = np.arange(8000)
print(a1.size)
print(a1.size*a1.itemsize)

<class 'range'>
For List
28
224000


For Numpy
8000
64000


20. Write a program to show how Numpy taking less time compared to Python List?

In [ ]:
import time
import sys

In [ ]:
size = 100000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list itemwise sum
start = time.time()
result = [ (x +y) for x,y in zip(l1,l2)]
print((time.time() - start)*1000)

#numpy array itemwise sum
start = time.time()
result = n1+n2
print((time.time() - start)*1000)

20.681381225585938
2.5787353515625
